### ISSUE TITLE
How to add new python package 

### ISSUE THREAD

**Issue by tzupingkao** [ainsophical/DROID_PYTHON#5]
I download numpy ( [compiled for ARM use](https://archlinuxarm.org/packages/arm/python-numpy) ) and wish to add it in SL4A project.
Could you tell me how to add the "numpy files" dir into corresponded *.zip?

As my test result, I can not import numpy successfully.

**Comment by ainsophical** [comment]
You'll want to unzip the modules zip, add package and re-zip.

`/apk-2.7/app/src/main/res/raw/python_extras_27.zip`

In the zip archive, you'll put your package into this directory:

`/packages/python/`

To save on space you can run your package directory against `python -m compileall` and remove all the .py files before you put into the archive as well. Otherwise, you have useless .py files once the package is compiled for the first time on the device.

**Comment by IqoqoService** [comment]
@tzupingkao Did you manage to add numpy? Which files did you copy and did you have to add any dependencies? 

Thanks

**Comment by michaelrinderle** [comment]
I'm pretty sure numpy has c binary dependencies, you'd need to get numpy source and compile for arm with android-ndk.
